In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 22.6 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 42.8 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
import pandas as pd
url = 'https://raw.githubusercontent.com/avelareliandro/ProjetoImobiliario/refs/heads/main/alunos.csv'
df_alunos = pd.read_csv(url)
df_alunos.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [6]:
df_alunos.shape

(18, 4)

In [7]:
df_alunos.info()
# A função info() é usada para obter uma visão geral do DataFrame, incluindo o número de entradas, o número de colunas, os tipos de dados de cada coluna e a quantidade de valores não nulos em cada coluna. Isso é útil para entender a estrutura dos dados e identificar possíveis problemas, como valores ausentes ou tipos de dados incorretos.

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      18 non-null     str
 1   Idade     18 non-null     int64
 2   Notas     12 non-null     float64
 3   Aprovado  18 non-null     bool
dtypes: bool(1), float64(1), int64(1), str(1)
memory usage: 582.0 bytes

In [8]:
df_alunos.shape
# A função shape é usada para obter as dimensões do DataFrame, ou seja, o número de linhas e colunas. O resultado é uma tupla onde o primeiro elemento representa o número de linhas e o segundo elemento representa o número de colunas. Isso é útil para entender a quantidade de dados que estamos lidando e para verificar se o DataFrame foi carregado corretamente.

(18, 4)

In [9]:
df_alunos[['Nome', 'Aprovado']]
# A sintaxe df_alunos[['Nome', 'Aprovado']] é usada para selecionar apenas as colunas "Nome" e "Aprovado" do DataFrame df_alunos. O resultado será um novo DataFrame contendo apenas essas duas colunas, o que pode ser útil para focar em informações específicas ou para realizar análises mais direcionadas.

         Nome  Aprovado
0         Ary      True
1         Ana     False
2       Cátia     False
3       Denis     False
4        Beto      True
5       Bruna     False
6        Dara      True
7      Carlos      True
8       Alice     False
9       Vitor     False
10     Daniel     False
11       Igor     False
12  Sthefanie      True
13      Mirla      True
14      Paulo     False
15     Mylena      True
16      Lucas     False
17      Nadia      True

In [10]:
df_alunos.head(7)
# A função head() é usada para exibir as primeiras linhas de um DataFrame. Ao passar o argumento 7, estamos solicitando que sejam exibidas as primeiras 7 linhas do DataFrame df_alunos. Isso é útil para obter uma visão rápida dos dados e verificar se o DataFrame foi carregado corretamente, além de permitir uma inspeção inicial dos valores contidos nas colunas.

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [11]:
df_alunos.tail()
# A função tail() é usada para exibir as últimas linhas de um DataFrame. Por padrão, ela exibe as últimas 5 linhas, mas você pode passar um argumento para especificar quantas linhas deseja ver. Isso é útil para obter uma visão rápida do final dos dados e verificar se o DataFrame foi carregado corretamente, além de permitir uma inspeção inicial dos valores contidos nas colunas.

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

In [12]:
type(df_alunos)
# A função type() é usada para verificar o tipo de um objeto em Python. Ao passar o DataFrame df_alunos como argumento, estamos verificando se ele é realmente um DataFrame do

pandas.DataFrame